---

- name: Update apt packages
  apt:
    update_cache: true
  become: true
  tags:
    - apt

- name: Packages
  include_tasks: packages.yaml
  tags:
    - always

- name: FFMPEG build and install
  include_tasks: ffmpeg_motion.yaml
  tags:
    - always

- name: SQLITE3 config
  include_tasks: sql3.yaml
  tags:
    - sql3

- name: Create /mnt/motion directory
  file:
    path: /mnt/motion
    state: directory
    owner: andre
    group: andre
    mode: '0755'
  become: true
  tags:
    - config

- name: Remove default nginx
  shell: |
    if [ ! -f "/etc/nginx/sites-enabled/default" ]; then
      rm /etc/nginx/sites-enabled/default
    fi
  become: true
  tags:
    - nginx
    - install
    - config

- name: Install nginx .conf
  template:
    src: "etc/nginx/sites-enabled/{{ item }}"
    dest: /etc/nginx/sites-enabled/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion_files.conf
  become: true
  tags:
    - config
    - install


- name: Install motion's and ro-overlay services
  template:
    src: "etc/systemd/system/{{ item }}"
    dest: /etc/systemd/system/
  become: true
  loop:
    - motion.service
    - ro_overlay.service
  tags:
    - install

- name: Enable and services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:
    - motion 
    - nginx    
  become: true
  tags:
    - enable

- name: Install read only overlay mount .service script
  copy:
    src: ro_overlay.sh
    dest: /usr/bin/
    mode: 0700
  become: true
  tags:
    - install

- name: Enable but dont start overlay mount .service
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: stopped
    daemon_reload: true
    force: true
  loop:
    - ro_overlay
  become: true
  tags:
    - enable
    - never 


