---

- name: Update apt packages
  apt:
    update_cache: true
  become: true
  tags:
    - apt

- name: Packages + FFMPEG build and install
  include_tasks: ffmpeg_motion.yml
  tags:
    - always

- name: SQLITE3 config
  include_tasks: sql3.yml
  tags:
    - sql3

# - name: fstab to mount nfs shared folder
#   ansible.builtin.lineinfile:
#     path: /etc/fstab
#     line: orangepizero2:/mnt/motion               /mnt/motion      nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
#     create: yes
#   become: true
#   tags:
#     - config

- name: Create /mnt/motion directory
  file:
    path: /mnt/motion
    state: directory
    owner: andre
    group: andre
    mode: '0755'
  become: true
  tags:
    - config

- name: Mount an nfs shared folder
  ansible.posix.mount:
    src: orangepizero2:/mnt/motion
    path: /mnt/motion
    opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
    state: mounted
    fstype: nfs
  become: true
  tags:
    - config

# per ansible repository issue: must include allways tags on include_tasks
# https://github.com/ansible/ansible/issues/41540#issuecomment-397341326

- name: Install nginx .conf
  template:
    src: "etc/nginx/sites-enabled/{{ item }}"
    dest: /etc/nginx/sites-enabled/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion_files.conf
  become: true
  tags:
    - config
    - install

- name: Remove default nginx
  shell: |
    if [ ! -f "/etc/nginx/sites-enabled/default" ]; then
      rm /etc/nginx/sites-enabled/default
    fi
  become: true
  tags:
    - nginx

- name: Install motion's and ro-overlay services
  template:
    src: "etc/systemd/system/{{ item }}"
    dest: /etc/systemd/system/
  become: true
  loop:
    - motion.service
    - motion_helper.service
    - ro_overlay.service
  tags:
    - install

- name: Install systemd-python package to e-mail journalctl error logs
  ansible.builtin.pip:
    name: systemd-python

- name: Enable and services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:
    - motion
    - motion_helper
    - nginx
  become: true
  tags:
    - enable

- name: Install read only overlay mount .service script
  copy:
    src: ro_overlay.sh
    dest: /usr/bin/
    mode: 0700
  become: true
  tags:
    - install

- name: Enable but dont start overlay mount .service
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: stopped
    daemon_reload: true
    force: true
  loop:
    - ro_overlay
  become: true
  tags:
    - enable
    - never 


