
# TODO add repositories bellow 
# from armibian page - Enable 3D Acceleration (Ubuntu variant only)
# not sure need these repositories
# sudo add-apt-repository ppa:liujianfeng1994/panfork-mesa
# sudo add-apt-repository ppa:liujianfeng1994/rockchip-multimedia
# sudo apt update
# sudo apt install mali-g610-firmware rockchip-multimedia-config

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tzdata
    - curl
    - htop
    - git
    - tmux
    - lsof
    - python3
    - python3-dev
    - python3-pip
    - nginx
    - nginx-extras
    # motion required
    - autoconf
    - automake
    - autopoint
    - build-essential
    - pkg-config
    - libtool
    - libzip-dev
    - libjpeg-dev
    - libwebp-dev
    - libsqlite3-dev
    - gettext
    - libmicrohttpd-dev
    - unzip
    # systemd.journal python package needed
    - libsystemd-dev
    # nfs mount shared from orangepizero2
    - nfs-common
    # ffmpeg rkmpp hardware decoder
    - libyuv-dev
    - librga2
    - librga-dev 
    - libdrm-dev
    - librockchip-mpp-dev 
    - libv4l-dev
    - v4l2loopback-utils
    - v4l2loopback-dkms
  become: true
  tags:
    - apt

- name: Install pip python packages
  ansible.builtin.pip:
    name:
      - ansible
      - pandas
      - pyserial 
      - systemd-python
