---
- name: Update apt packages
  apt:
    update_cache: true
  become: true

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tzdata
    - cmake
    - curl
    - htop
    - git
    - tmux
    - python3.8
    - nginx
    - nginx-extras
    # motion required
    - autoconf
    - automake
    - autopoint
    - build-essential
    - pkgconf
    - libtool
    - libzip-dev
    - libjpeg-dev
    - libwebp-dev
    - libsqlite3-dev
    - gettext
    - libmicrohttpd-dev
    - unzip
  become: true
  tags:
    - apt

# doesnt work for whatever reason
# - name: Create temporary build directory for ffmpeg and motion build
#   tempfile:
#     state: directory
#     suffix: build
#   register: tmp_dir

- name: Copy install scripts ffmpeg and motion
  copy:
    src: "{{ item }}"
    dest: "{{ build_folder }}"
    mode: 0777
  loop:
    - ffmpeg_install.sh
    - motion_install.sh
    - RTSP_lower_transport_TCP.patch
  tags:
    - build

- name: Build ffmpeg nvmpi library and ffmpeg
  shell: "{{ build_folder }}/ffmpeg_install.sh"
  tags:
    - build

- name: Install ffmpeg nvmpi library and ffmpeg
  shell: |
    cd "{{ build_folder }}/jetson-ffmpeg/build"
    make install
    ldconfig
    cd ffmpeg
    make install
    ldconfig
  become: true
  tags:
    - build

- name: Build motion
  shell: "{{ build_folder }}/motion_install.sh"
  tags:
    - build

- name: Install motion
  shell: |
    cd "{{ build_folder }}/{{ motion_build_folder }}"
    cp src/motion  /usr/local/bin/motiond
    chmod 777 /usr/local/bin/motiond
  become: true
  tags:
    - install

- name: Mount 15th partition for Motion rec.media ~95GB (Gparted)
  ansible.posix.mount:
    path: /mnt/motion_data
    src: /dev/mmcblk0p15
    fstype: ext4
    opts: "defaults"
    state: mounted
  become: true
  tags:
    - mount

# since opts 'user, umask=0000' above is not working
- name: chown /etc/motion_data since mount did not work
  shell: "chown -R andre:andre {{ motion_storage_dir }}"
  become: true
    - mount

- name: Add ips of network cameras in /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  loop:
    - '#from archer c7 router dhcp reservation && security -> mac binding'
    - '192.168.0.179   ipcam.street # 9C-A3-A9-6A-87-5B'
    - '192.168.0.12    ipcam.frontwall # A0-9F-10-00-93-C6'
    - '192.168.0.11    ipcam.kitchen # A0-9F-10-01-30-D8'
    - '192.168.0.13    ipcam.garage #A0-9F-10-01-30-D2'
  become: true
  tags:
    - config

- name: Install nginx .conf
  template:
    src: "etc/nginx/sites-enabled/{{ item }}"
    dest: /etc/nginx/sites-enabled/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion_files.conf
  become: true
  tags:
    - config
    - install

- name: Install motion_helper.py
  template:
    src: usr/bin/motion_helper.py
    dest: /usr/bin/motion_helper.py
    owner: andre
    group: andre
    mode: 0755
  become: true
  tags:
    - install

- name: Install motion_helper service
  template:
    src: etc/systemd/system/motion_helper.service
    dest: /etc/systemd/system/motion_helper.service
  become: true
  tags:
    - install

- name: Install motion service
  template:
    src: etc/systemd/system/motion.service
    dest: /etc/systemd/system/motion.service
  become: true
  tags:
    - install

- name: Install motion_helper.py
  template:
    src: usr/bin/motion_helper.py
    dest: /usr/bin/motion_helper.py
    owner: andre
    group: andre
    mode: 0755
  become: true
  tags:
    - install
 
- name: Install motion_helper service
  template:
    src: etc/systemd/system/motion_helper.service
    dest: /etc/systemd/system/motion_helper.service
  become: true
  tags:
    - install

- name: Install motion service
  template:
    src: etc/systemd/system/motion.service
    dest: /etc/systemd/system/motion.service
  become: true
  tags:
    - install

- name: Install motion *.conf and mask files
  template:
    src: "usr/local/etc/motion/{{ item }}"
    dest: /usr/local/etc/motion/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion.conf
    - frontwall.conf
    - garage.conf
    - kitchen.conf
    - street.conf
    - mask_camera_low.pgm
    - mask_camera_street.pgm
    - mask_camera.pgm
  become: true
  tags:
    - config
    - install