---
- name: Update apt packages
  apt:
    update_cache: true
  become: true
  tags:
    - apt

# jetson-ffmpeg only requeriment
- name: Install nvidia multimedia api
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nvidia-l4t-jetson-multimedia-api
  become: true
  tags:
    - apt

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tzdata
    - cmake
    - curl
    - htop
    - git
    - tmux
    - lsof
    - python3
    - python3-numpy
    - nginx
    - nginx-extras
    # motion required
    - autoconf
    - automake
    - autopoint
    - build-essential
    - pkg-config
    - libtool
    - libzip-dev
    - libjpeg-dev
    - libwebp-dev
    - libsqlite3-dev
    - gettext
    - libmicrohttpd-dev
    - unzip
  become: true
  tags:
    - apt

# doesnt work for whatever reason
# - name: Create temporary build directory for ffmpeg and motion build
#   tempfile:
#     state: directory
#     suffix: build
#   register: tmp_dir

- name: Copy install scripts ffmpeg and motion
  copy:
    src: "{{ item }}"
    dest: "{{ build_folder }}"
    mode: 0777
  loop:
    - nvmpi_install.sh
    - ffmpeg_build.sh
    - motion_build.sh
    - RTSP_lower_transport_TCP.patch
    - time_t.patch
    - sqlite3_threadsafe.patch
  tags:
    - build

- name: Build nvmpi library needed for jetson-ffmpeg - Install:/usr/local/lib
  shell: "{{ build_folder }}/nvmpi_install.sh"
  become: true
  tags:
    - build

- name: Build ffmpeg
  shell: "{{ build_folder }}/ffmpeg_build.sh"
  tags:
    - build

- name: Install ffmpeg library
  shell: |
    cd "{{ build_folder }}/ffmpeg"
    make install
    ldconfig
  become: true
  tags:
    - install

- name: Build motion
  shell: "{{ build_folder }}/motion_build.sh"
  tags:
    - build

- name: Install motion
  shell: |
    cd "{{ build_folder }}/{{ motion_build_folder }}"
    cp src/motion  /usr/local/bin/motiond
    chmod 777 /usr/local/bin/motiond
  become: true
  tags:
    - install

- name: Install motion_helper.py
  template:
    src: usr/bin/motion_helper.py
    dest: /usr/bin/motion_helper.py
    owner: andre
    group: andre
    mode: 0755
  become: true
  tags:
    - install

- name: Install motion *.conf and mask files
  template:
    src: "usr/local/etc/motion/{{ item }}"
    dest: /usr/local/etc/motion/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion.conf
    - frontwall.conf
    - garage.conf
    - kitchen.conf
    - street.conf
    - new.conf
    - mask_camera_low.pgm
    - mask_camera_street.pgm
  become: true
  tags:
    - config
    - install

- name: Mount Motion Ext Usb HDD 568 GB
  ansible.posix.mount:
    path: "{{ motion_storage_dir }}"
    src: /dev/sda1
    fstype: ext4
    opts: "defaults"
    state: mounted
  become: true
  tags:
    - mount

# since opts 'user, umask=0000' above is not working
- name: chown motion_storage folder since mount did not work
  shell: "chown -R andre:andre {{ motion_storage_dir }}"
  become: true
  tags:
    - mount

# sudo timedatectl set-timezone America/Sao_Paulo
- name: Set timezone to America/Sao_Paulo
  shell: /usr/bin/timedatectl set-timezone America/Sao_Paulo
  become: true
  tags:
    - config

- name: Install nginx .conf
  template:
    src: "etc/nginx/sites-enabled/{{ item }}"
    dest: /etc/nginx/sites-enabled/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion_files.conf
  become: true
  tags:
    - config
    - install

- name: Remove default nginx
  shell: |
    if [ ! -f "/etc/nginx/sites-enabled/default" ]; then
      rm /etc/nginx/sites-enabled/default
    fi
  become: true
  tags:
    - nginx
