---

- name: Packages + FFMPEG build and install
  include_tasks: ffmpeg_motion.yml
  tags:
    - always

- name: SQLITE3 config
  include_tasks: sql3.yml
  tags:
    - sql3

# per ansible repository issue: must include allways tags on include_tasks
# https://github.com/ansible/ansible/issues/41540#issuecomment-397341326

- name: Update network conf
  template:
    src: etc/netplan/netcfg.yaml
    dest: /etc/netplan/netcfg.yaml
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - config

- name: Apply netplan
  command: netplan apply
  async: 45
  become: true
  tags:
    - config
    - netplan

- name: Install motion's and ro-overlay services
  template:
    src: "etc/systemd/system/{{ item }}"
    dest: /etc/systemd/system/
  become: true
  loop:
    - motion.service
    - motion_helper.service
    - ro_overlay.service
  tags:
    - install

- name: Install rsyslog configuration
  template:
    src: "etc/{{ item }}"
    dest: /etc/
  become: true
  loop:
    - rsyslog.conf
  tags:
    - install
    - rsyslog

- name: Install rsyslog configuration
  template:
    src: "etc/{{ item }}"
    dest: /etc/rsyslog.d/
  become: true
  loop:
    - rsyslog.d/50-default.conf
  tags:
    - install
    - rsyslog

- name: Install systemd-python package to e-mail journalctl error logs
  ansible.builtin.pip:
    name: systemd-python

- name: Enable and services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:
    - motion
    - motion_helper
    - nginx
    - rsyslog
  become: true
  tags:
    - enable

- name: Install read only overlay mount .service script
  copy:
    src: ro_overlay.sh
    dest: /usr/bin/
    mode: 0700
  become: true
  tags:
    - install

- name: Enable but dont start overlay mount .service
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: stopped
    daemon_reload: true
    force: true
  loop:
    - ro_overlay
  become: true
  tags:
    - enable
