---

- name: Packages + FFMPEG build and install
  include_tasks: ffmpeg_motion.yml
  tags:
    - always

- name: SQLITE3 config
  include_tasks: sql3.yml
  tags:
    - always

# per ansible repository issue: must include allways tags on include_tasks
# https://github.com/ansible/ansible/issues/41540#issuecomment-397341326
        
- name: Update network conf
  template:
    src: etc/netplan/netcfg.yaml
    dest: /etc/netplan/netcfg.yaml
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - config

- name: Apply netplan
  command: netplan apply
  async: 45
  become: true
  tags:
    - config

- name: Enable and start motion and nginx services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:    
    - motion_helper
    - motion
    - nginx
  become: true
  tags:
    - enable

# read-only prevent filesystem  corruption when energy goes down
# to revert back
# chattr -R -i /boot /lib /opt /usr /bin /sbin /etc 
- name: Set everything read only with chattr +i (imutable) ?? will work ??
  shell: !
    chattr -R +i /boot /lib /opt /usr /bin /sbin /etc 
  become: true
  tags:
    - never
  # special tag never run unless --tags never
## What should be done is try mount /tmp /var as tmpfs

# I have played with script line bellow.
# to get which files were last modified recursivly inside current folder
# find $1 -type f -print0 | xargs -0 stat --format '%Y :%y %n' | sort -nr | cut -d: -f2- | head
