---

# first thing FIRST
- name: Set DNS server for systemd-resolved
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNS='
    line: DNS=192.168.0.1
  become: true
  tags:
    - config

- name: Apply systemd-resolved dns settings above
  shell: |
    rm /etc/resolv.conf
    ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
    systemctl restart systemd-resolved.service
  become: true
  tags:
    - config

#sudo rm /etc/resolv.conf
#sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
# sudo dpkg-reconfigure resolvconf
# and restart sudo systemctl restart systemd-resolved.service

- name: Update network conf
  template:
    src: etc/netplan/netcfg.yaml
    dest: /etc/netplan/netcfg.yaml
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - config

- name: Apply netplan
  command: netplan apply
  async: 45
  become: true
  tags:
    - config
    - netplan  

- name: Update apt packages
  apt:
    update_cache: true
  become: true
  tags:
    - apt

- name: Packages + FFMPEG build and install
  include_tasks: ffmpeg_motion.yml
  tags:
    - always

- name: SQLITE3 config
  include_tasks: sql3.yml
  tags:
    - sql3

# must ssh-keygen and ssh-copy -i on andre@orangepi before this
- name: Jetson nano fstab to mount ssh shared folder
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: orangepi:/mnt/motion               /mnt/motion      nfs defaults,_netdev 0 0
    create: yes

# per ansible repository issue: must include allways tags on include_tasks
# https://github.com/ansible/ansible/issues/41540#issuecomment-397341326

- name: Install nginx .conf
  template:
    src: "etc/nginx/sites-enabled/{{ item }}"
    dest: /etc/nginx/sites-enabled/
    owner: andre
    group: andre
    mode: 0640
  loop:
    - motion_files.conf
  become: true
  tags:
    - config
    - install

- name: Remove default nginx
  shell: |
    if [ ! -f "/etc/nginx/sites-enabled/default" ]; then
      rm /etc/nginx/sites-enabled/default
    fi
  become: true
  tags:
    - nginx

- name: Install motion's and ro-overlay services
  template:
    src: "etc/systemd/system/{{ item }}"
    dest: /etc/systemd/system/
  become: true
  loop:
    - motion.service
    - motion_helper.service
    - ro_overlay.service
  tags:
    - install

- name: Install systemd-python package to e-mail journalctl error logs
  ansible.builtin.pip:
    name: systemd-python

- name: Enable and services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:
    - motion
    - motion_helper
    - nginx
    - rsyslog
  become: true
  tags:
    - enable

- name: Install read only overlay mount .service script
  copy:
    src: ro_overlay.sh
    dest: /usr/bin/
    mode: 0700
  become: true
  tags:
    - install

- name: Enable but dont start overlay mount .service
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: stopped
    daemon_reload: true
    force: true
  loop:
    - ro_overlay
  become: true
  tags:
    - enable
    - never 


