---

- name: Packages + FFMPEG build and install
  include_tasks: ffmpeg_motion.yml
  tags:
    - always

- name: SQLITE3 config
  include_tasks: sql3.yml
  tags:
    - always

# per ansible repository issue: must include allways tags on include_tasks
# https://github.com/ansible/ansible/issues/41540#issuecomment-397341326

- name: Enable and start motion and nginx services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
    force: true
  loop:
    - motion_helper
    - motion
    - nginx
  become: true
  tags:
    - enable
