---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
  # wifis:
  #   wlan0:
  #     dhcp4: true
  #     dhcp4-overrides:
  #       use-dns: no
  #     nameservers:
  #       addresses: [8.8.8.8,8.8.4.4]
  #     access-points:
  #       YOUR_ACCESS_POINT:
  #         password: WIFI_PASSWORD
  # to fix problems with systemd-resolved.service trying
  # to be the only dns-server
  # https://askubuntu.com/a/1329397/52310
