---
build_folder: /home/andre
motion_storage_size: 350
motion_storage_dir: /mnt/motion
motion_build_folder: motion-src
motion_db:
  file: motion.db
  sql_query_start: >
    INSERT INTO events(cam, name, start) 
    VALUES(%t, '%$', %{eventtime});
  sql_query: >
    UPDATE events SET pfile='%f',nchange_pixels=%D,width=%w,height=%h,motion_width=%i,motion_height=%J,motion_cx=%K,motion_cy=%L,threshold=%o,fps=%{fps},frame=%q 
    WHERE start=%{eventtime} AND cam=%t AND %n=1; 
    UPDATE events SET mfile='%f' 
    WHERE start=%{eventtime} AND cam=%t AND %n=8; 
  sql_query_stop: >
    UPDATE events SET stop=%{timet}
    WHERE start=%{eventtime} AND cam=%t;
# > multiline string without linebreaks

# file type '%n' or 1 for picture or 8 for movie motion
#define FTYPE_IMAGE            1
#define FTYPE_IMAGE_SNAPSHOT   2
#define FTYPE_IMAGE_MOTION     4
#define FTYPE_MPEG             8
#define FTYPE_MPEG_MOTION     16
#define FTYPE_MPEG_TIMELAPSE  32

# Conversion Specifiers
# %Y	year	                     %m	month	                      %d	day
# %H	hour	                     %M	minute	                    %S	second
# %T	HH:MM:SS	                 %v	event	                      %q	frame number
# %t	camera id number	         %D	changed pixels	            %N	noise level
# %w	width of the image	       %h	height of the image	        %i	width of motion area
# %J	height of motion area	     %K	X coord. motion center	    %L	Y coordinates of motion center
# %C	value by text_event	       %f	filename with full path	    %n	number indicating filetype
# %o	threshold	                 %Q	Number labels despeckle	    %{dbeventid}	See sql_query_start
# %$	camera name	               %{fps}	current fps	            %{host}	name of computer running Motion
# %{ver}	The version of Motion	 %{eventtime}	unix epoch event time %{timet} unix epoch time